import Link from 'next/link'
import { ArrowRight, BadgeCheck, Boxes, Route, ShieldCheck, Sprout, Wallet } from 'lucide-react'

const steps = [['Register & verify', 'Role-based onboarding, mobile OTP and Aadhaar-consent verification.'], ['Plan harvests', 'Farmers register crop volume and harvest windows with or without an FPO.'], ['Aggregate & grade', 'Collection batches turn into AI-assisted, human-approved verified inventory.'], ['Match & settle', 'Verified buyers order, routes are planned, and passbooks show settlement.']]
export default function HomePage() {
  return <main className='min-h-screen bg-background'><header className='mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8'><Link href='/' className='flex items-center gap-2 font-serif text-2xl font-bold'><span className='grid size-10 place-items-center rounded-xl bg-primary text-primary-foreground'><Sprout className='size-6' /></span>AgriLink</Link><nav className='flex items-center gap-3 text-sm font-semibold'><Link className='hidden text-muted-foreground sm:block' href='#how-it-works'>How it works</Link><Link className='rounded-xl border border-border px-4 py-2.5' href='/login'>Sign in</Link><Link className='rounded-xl bg-primary px-4 py-2.5 text-primary-foreground' href='/signup'>Get started</Link></nav></header>
    <section className='mx-auto grid max-w-7xl gap-12 px-5 py-16 sm:px-8 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:py-24'><div><p className='inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1.5 text-xs font-semibold text-primary'><BadgeCheck className='size-4' /> Traceable produce. Trusted trade.</p><h1 className='mt-6 max-w-3xl font-serif text-5xl font-bold leading-[1.03] tracking-tight sm:text-7xl'>From harvest to a fair, verified market.</h1><p className='mt-6 max-w-2xl text-lg leading-8 text-muted-foreground'>AgriLink connects farmers, FPOs, buyers and logistics teams through one accountable supply chain—crop planning, quality checks, fulfillment and settlement included.</p><div className='mt-8 flex flex-wrap gap-3'><Link href='/signup' className='inline-flex items-center gap-2 rounded-xl bg-primary px-5 py-3 font-semibold text-primary-foreground'>Create an account <ArrowRight className='size-4' /></Link><Link href='/login' className='rounded-xl border border-border px-5 py-3 font-semibold'>Open workspace</Link></div></div><div className='rounded-3xl border border-border bg-card p-6 shadow-sm'><p className='text-xs font-semibold uppercase tracking-[.2em] text-primary'>The verified supply chain</p><div className='mt-6 space-y-4'>{[['Farmer harvest', 'Crop quantity and availability'], ['FPO aggregation', 'Batch, weight and traceability'], ['Quality verification', 'AI-assisted visual grade + approval'], ['Buyer fulfillment', 'Controlled orders, route and settlement']].map(([title, detail], index) => <div key={title} className='flex gap-4 rounded-2xl bg-muted/60 p-4'><span className='grid size-8 shrink-0 place-items-center rounded-full bg-primary text-sm font-bold text-primary-foreground'>{index + 1}</span><div><p className='font-semibold'>{title}</p><p className='text-sm text-muted-foreground'>{detail}</p></div></div>)}</div></div></section>
    <section id='how-it-works' className='border-y border-border bg-card'><div className='mx-auto max-w-7xl px-5 py-16 sm:px-8'><p className='text-xs font-semibold uppercase tracking-[.2em] text-primary'>One connected flow</p><h2 className='mt-3 font-serif text-4xl font-bold'>Every action has a next step.</h2><div className='mt-9 grid gap-5 md:grid-cols-2 xl:grid-cols-4'>{steps.map(([title, detail], i) => <article key={title} className='rounded-2xl border border-border p-5'><p className='font-mono text-xs text-primary'>0{i + 1}</p><h3 className='mt-5 text-lg font-semibold'>{title}</h3><p className='mt-2 text-sm leading-6 text-muted-foreground'>{detail}</p></article>)}</div></div></section>
    <section className='mx-auto grid max-w-7xl gap-5 px-5 py-16 sm:grid-cols-3 sm:px-8'><Feature icon={<ShieldCheck />} title='Identity-aware access' text='Protected workspaces, role-specific profiles and verification status.' /><Feature icon={<Boxes />} title='Verified inventory' text='Only recorded, graded supply moves forward to the market.' /><Feature icon={<Route />} title='Connected delivery' text='Collection, dispatch, delivery and settlement remain traceable.' /></section>
    <footer className='border-t border-border px-5 py-8 text-center text-sm text-muted-foreground'>AgriLink · built for accountable farm-to-market trade</footer>
  </main>
}
function Feature({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <article className='rounded-2xl border border-border bg-card p-6'><div className='text-primary'>{icon}</div><h3 className='mt-4 font-serif text-2xl font-bold'>{title}</h3><p className='mt-2 text-sm leading-6 text-muted-foreground'>{text}</p></article> }
