'use client'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Loader2, ShieldCheck } from 'lucide-react'
import { getAuthClient } from '@/lib/auth-client'
type Data = { profiles: Array<{ id: string; full_name: string; role: string; mobile_number: string | null; verification_status: string; last_login_at: string | null; last_logout_at: string | null }>; activities: Array<{ id: string; user_id: string | null; event_type: string; created_at: string }>; pending_reviews: Array<{ id: string; crop: string; quantity_kg: number; purpose: string | null; created_at: string }> }
export function AdminPortal() {
  const router = useRouter(), [data, setData] = useState<Data | null>(null), [error, setError] = useState('')
  async function load() { try { const { data: session } = await getAuthClient().auth.getSession(); if (!session.session) return router.replace('/login'); const response = await fetch('/api/admin/reviews', { headers: { Authorization: 'Bearer ' + session.session.access_token } }); const json = await response.json(); if (!response.ok) throw new Error(json.error); setData(json) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load admin data.') } }
  useEffect(() => { load() }, [])
  async function review(id: string, decision: 'approved' | 'rejected') { const { data: session } = await getAuthClient().auth.getSession(); const response = await fetch('/api/admin/reviews', { method: 'PATCH', headers: { Authorization: 'Bearer ' + session.session?.access_token, 'Content-Type': 'application/json' }, body: JSON.stringify({ request_id: id, decision }) }); if (!response.ok) setError((await response.json()).error); else load() }
  if (error) return <main className='grid min-h-screen place-items-center p-5'><div className='rounded-2xl border border-border bg-card p-6 text-center'><p className='font-semibold text-destructive'>{error}</p><button onClick={() => router.push('/portal')} className='mt-4 text-sm font-semibold text-primary'>Return to workspace</button></div></main>
  if (!data) return <main className='grid min-h-screen place-items-center'><Loader2 className='animate-spin text-primary' /></main>
  return <main className='mx-auto max-w-7xl p-5 py-10 sm:p-8'><div className='flex items-center justify-between'><div><p className='text-xs font-semibold uppercase tracking-[.2em] text-primary'>Control centre</p><h1 className='mt-2 font-serif text-4xl'>Admin portal</h1></div><ShieldCheck className='size-10 text-primary' /></div><div className='mt-8 grid gap-5 md:grid-cols-3'><Card label='Registered users' value={String(data.profiles.length)} /><Card label='Verified profiles' value={String(data.profiles.filter(p => p.verification_status === 'verified').length)} /><Card label='Large-order reviews' value={String(data.pending_reviews.length)} /></div><section className='mt-8 rounded-2xl border border-border bg-card p-5'><h2 className='font-serif text-2xl'>Buyer requests awaiting review</h2><div className='mt-4 space-y-3'>{data.pending_reviews.length ? data.pending_reviews.map(r => <div key={r.id} className='flex flex-wrap items-center justify-between gap-4 rounded-xl bg-muted p-4'><div><p className='font-semibold'>{r.quantity_kg} kg · {r.crop}</p><p className='mt-1 text-sm text-muted-foreground'>{r.purpose}</p></div><div className='flex gap-2'><button onClick={() => review(r.id, 'approved')} className='rounded-lg bg-primary px-3 py-2 text-sm font-semibold text-primary-foreground'>Approve</button><button onClick={() => review(r.id, 'rejected')} className='rounded-lg border border-border px-3 py-2 text-sm font-semibold'>Reject</button></div></div>) : <p className='text-sm text-muted-foreground'>No buyer requests require review.</p>}</div></section><section className='mt-8 rounded-2xl border border-border bg-card p-5'><h2 className='font-serif text-2xl'>User activity</h2><div className='mt-4 overflow-x-auto'><table className='w-full text-left text-sm'><thead className='text-muted-foreground'><tr><th className='pb-3'>User</th><th className='pb-3'>Role</th><th className='pb-3'>Verification</th><th className='pb-3'>Last login</th></tr></thead><tbody>{data.profiles.map(p => <tr key={p.id} className='border-t border-border'><td className='py-3 font-medium'>{p.full_name}</td><td className='py-3 capitalize'>{p.role}</td><td className='py-3 capitalize'>{p.verification_status}</td><td className='py-3'>{p.last_login_at ? new Date(p.last_login_at).toLocaleString() : '—'}</td></tr>)}</tbody></table></div></section></main>
}
function Card({ label, value }: { label: string; value: string }) { return <div className='rounded-2xl border border-border bg-card p-5'><p className='text-sm text-muted-foreground'>{label}</p><p className='mt-2 font-serif text-4xl font-bold'>{value}</p></div> }
