'use client'

import { useMemo, useState } from 'react'
import {
  ArrowDownRight, ArrowUpRight, Bell, Camera, Check, ChevronDown, CircleDollarSign,
  ClipboardList, Cloud, Droplets, LayoutDashboard, Leaf, MapPin, Menu, PackageCheck,
  Route, Send, ShieldCheck, Sprout, Truck, Users, Wheat, X, Phone, Smartphone,
  Warehouse, BadgeCheck, AlertTriangle, Plus, ChevronRight, Receipt, Banknote,
} from 'lucide-react'

type Role = 'Coordinator' | 'Buyer' | 'Farmer'
type Screen = 'Overview' | 'Orders' | 'Farmer network' | 'Collection & grade' | 'Routes' | 'Settlements'

const navItems = [
  { label: 'Overview', icon: LayoutDashboard }, { label: 'Orders', icon: ClipboardList, count: '03' },
  { label: 'Farmer network', icon: Users }, { label: 'Collection & grade', icon: Camera },
  { label: 'Routes', icon: Route }, { label: 'Settlements', icon: CircleDollarSign },
]
const channels = ['SMS', 'WhatsApp', 'IVR voice', 'Coordinator list']
const farmers = [
  { name: 'Ramesh Kumar', village: 'Kheda', kg: 50, status: 'Accepted', color: 'bg-primary' },
  { name: 'Savitri Devi', village: 'Borsad', kg: 70, status: 'Accepted', color: 'bg-amber-700' },
  { name: 'Mohan Lal', village: 'Vasad', kg: 80, status: 'Accepted', color: 'bg-sky-700' },
  { name: 'Lakshmi Bai', village: 'Kheda', kg: 30, status: 'Standby', color: 'bg-stone-500' },
]
const SHELF_LIFE_ROUTING = {
  perishable: { maxDays: 5, channels: ['INSTITUTIONAL'] },
  semiPerishable: { maxDays: 60, channels: ['INSTITUTIONAL', 'FAIR_PRICE_SHOP', 'RESIDENTIAL_SOCIETY'] },
  shelfStable: { maxDays: 999, channels: ['INSTITUTIONAL', 'FAIR_PRICE_SHOP', 'RESIDENTIAL_SOCIETY'] },
}

function Badge({ children, tone = 'muted' }: { children: React.ReactNode; tone?: 'live' | 'cached' | 'muted' | 'good' | 'warn' }) {
  const styles = { live: 'bg-primary/10 text-primary', cached: 'bg-accent/15 text-accent-foreground', muted: 'bg-secondary text-muted-foreground', good: 'bg-primary/10 text-primary', warn: 'bg-accent/15 text-accent-foreground' }
  return <span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 font-mono text-[10px] uppercase tracking-wider ${styles[tone]}`}><span className={`size-1.5 rounded-full ${tone === 'live' || tone === 'good' ? 'bg-primary' : tone === 'warn' || tone === 'cached' ? 'bg-accent' : 'bg-muted-foreground'}`} />{children}</span>
}
function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-xl border border-border bg-card ${className}`}>{children}</section> }
function Button({ children, onClick, variant = 'primary', disabled = false }: { children: React.ReactNode; onClick?: () => void; variant?: 'primary' | 'secondary' | 'ghost'; disabled?: boolean }) { return <button disabled={disabled} onClick={onClick} className={`inline-flex min-h-10 items-center justify-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold transition hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-60 ${variant === 'primary' ? 'bg-primary text-primary-foreground shadow-sm' : variant === 'secondary' ? 'border border-border bg-secondary text-foreground' : 'text-primary hover:bg-secondary'}`}>{children}</button> }

export function AgriLinkDashboard() {
  const [role, setRole] = useState<Role>('Coordinator')
  const [activeNav, setActiveNav] = useState<Screen>('Overview')
  const [menuOpen, setMenuOpen] = useState(false)
  const [notified, setNotified] = useState(false)
  const [orderPosted, setOrderPosted] = useState(false)
  const [advancePaid, setAdvancePaid] = useState(false)
  const [grade, setGrade] = useState<'A' | 'B' | 'Rejected'>('A')
  const [gradeSaved, setGradeSaved] = useState(false)
  const [delivery, setDelivery] = useState<'pending' | 'confirmed' | 'flagged'>('pending')
  const [postedCrop, setPostedCrop] = useState('Tomato')
  const [postedQty, setPostedQty] = useState('200')
  const [showOrderForm, setShowOrderForm] = useState(false)

  const committed = useMemo(() => farmers.reduce((sum, farmer) => sum + farmer.kg, 0), [])
  const progress = Math.min(100, Math.round((committed / 200) * 100))
  const go = (screen: Screen) => { setActiveNav(screen); setMenuOpen(false) }
  const roleNav: Record<Role, Screen[]> = { Coordinator: navItems.map((item) => item.label as Screen), Buyer: ['Overview', 'Orders', 'Settlements'], Farmer: ['Overview', 'Farmer network', 'Collection & grade', 'Settlements'] }

  return <div className="min-h-screen bg-background text-foreground">
    <aside className="fixed inset-y-0 left-0 z-30 hidden w-64 flex-col border-r border-border bg-card lg:flex"><Brand /><Sidebar activeNav={activeNav} role={role} go={go} roleNav={roleNav} /></aside>
    <main className="lg:pl-64">
      <header className="sticky top-0 z-20 flex h-20 items-center justify-between border-b border-border bg-background/95 px-5 backdrop-blur-md sm:px-8 lg:px-10"><div className="flex items-center gap-3"><button className="lg:hidden" onClick={() => setMenuOpen(true)} aria-label="Open menu"><Menu className="size-5" /></button><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-muted-foreground">Tuesday · 14 October 2025</p><h1 className="font-serif text-xl font-bold tracking-tight sm:text-2xl">Good morning, {role === 'Farmer' ? 'Ramesh' : role === 'Buyer' ? 'Meera' : 'Anita'}</h1></div></div><div className="flex items-center gap-3"><button className="relative rounded-full p-2 text-muted-foreground hover:bg-secondary" aria-label="Notifications"><Bell className="size-5" /><span className="absolute right-1.5 top-1.5 size-1.5 rounded-full bg-accent" /></button><div className="hidden h-8 w-px bg-border sm:block" /><label className="flex items-center gap-2 rounded-full border border-border bg-card py-1.5 pl-3 pr-2 text-sm"><span className="hidden sm:inline text-muted-foreground">View as</span><select value={role} onChange={(e) => { const next = e.target.value as Role; setRole(next); setActiveNav('Overview') }} className="bg-transparent font-semibold outline-none"><option>Coordinator</option><option>Buyer</option><option>Farmer</option></select><ChevronDown className="size-3 text-muted-foreground" /></label></div></header>
      {menuOpen && <div className="fixed inset-0 z-40 bg-foreground/20 lg:hidden" onClick={() => setMenuOpen(false)}><div className="h-full w-72 border-r border-border bg-card p-5" onClick={(e) => e.stopPropagation()}><div className="mb-8 flex items-center gap-3"><Brand /><button className="ml-auto" onClick={() => setMenuOpen(false)} aria-label="Close menu"><X className="size-5" /></button></div><Sidebar activeNav={activeNav} role={role} go={go} roleNav={roleNav} mobile /></div></div>}
      <div className="mx-auto max-w-[1500px] px-5 py-8 sm:px-8 lg:px-10"><ScreenHeader role={role} activeNav={activeNav} onNew={() => setShowOrderForm(true)} />
        {showOrderForm && <OrderForm crop={postedCrop} setCrop={setPostedCrop} qty={postedQty} setQty={setPostedQty} onClose={() => setShowOrderForm(false)} onPost={() => { setOrderPosted(true); setShowOrderForm(false); go('Orders') }} />}
        {activeNav === 'Overview' && <Overview role={role} committed={committed} progress={progress} notified={notified} onNotify={() => setNotified(true)} onOrder={() => setShowOrderForm(true)} onRoute={() => go('Routes')} />}
        {activeNav === 'Orders' && <Orders role={role} orderPosted={orderPosted} onNew={() => setShowOrderForm(true)} advancePaid={advancePaid} onAdvance={() => setAdvancePaid(true)} notified={notified} onNotify={() => setNotified(true)} />}
        {activeNav === 'Farmer network' && <Network notified={notified} onNotify={() => setNotified(true)} />}
        {activeNav === 'Collection & grade' && <Collection grade={grade} setGrade={setGrade} saved={gradeSaved} onSave={() => setGradeSaved(true)} advancePaid={advancePaid} onAdvance={() => setAdvancePaid(true)} />}
        {activeNav === 'Routes' && <RoutesScreen delivery={delivery} setDelivery={setDelivery} />}
        {activeNav === 'Settlements' && <Settlements role={role} delivery={delivery} />}
      </div>
    </main>
  </div>
}

function Brand() { return <div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Sprout className="size-5" /></div><div><div className="font-serif text-xl font-bold tracking-tight">AgriLink</div><div className="font-mono text-[9px] uppercase tracking-[0.22em] text-muted-foreground">FARM TO COMMONS</div></div></div> }
function Sidebar({ activeNav, role, go, roleNav, mobile = false }: { activeNav: Screen; role: Role; go: (s: Screen) => void; roleNav: Record<Role, Screen[]>; mobile?: boolean }) { return <div className={`flex ${mobile ? 'flex-col' : 'flex-1 flex-col justify-between'} px-3 py-6`}><nav className="space-y-1"><div className="mb-4 px-3 font-mono text-[10px] font-medium uppercase tracking-[0.2em] text-muted-foreground">{role} workspace</div>{navItems.filter((item) => roleNav[role].includes(item.label as Screen)).map(({ label, icon: Icon, count }) => <button key={label} onClick={() => go(label as Screen)} className={`flex w-full items-center justify-between rounded-lg px-3 py-3 text-left text-sm transition-colors ${activeNav === label ? 'bg-primary text-primary-foreground shadow-sm' : 'text-muted-foreground hover:bg-secondary hover:text-foreground'}`}><span className="flex items-center gap-3"><Icon className="size-4" />{label}</span>{count && <span className="font-mono text-[10px]">{count}</span>}</button>)}</nav>{!mobile && <div className="rounded-xl border border-border bg-secondary/60 p-4"><div className="mb-3 flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Pilot volume</span><span className="size-2 rounded-full bg-primary" /></div><div className="mb-2 text-2xl font-semibold tracking-tight">77%</div><p className="text-xs leading-5 text-muted-foreground">of weekly FPO volume moved through confirmed orders.</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-border"><div className="h-full w-[77%] rounded-full bg-primary" /></div></div>}</div> }
function ScreenHeader({ role, activeNav, onNew }: { role: Role; activeNav: Screen; onNew: () => void }) { const copy: Record<Screen, string> = { Overview: 'Demand finds the harvest.', Orders: 'Orders before harvest.', 'Farmer network': 'The crop registry, activated.', 'Collection & grade': 'Trust at the collection point.', Routes: 'Every lot has a route.', Settlements: 'Transparent money movement.' }; return <div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs font-medium text-primary"><span className="size-2 rounded-full bg-primary" />{role} workspace · pilot live</div><h2 className="max-w-2xl font-serif text-4xl font-bold tracking-tight text-balance sm:text-5xl">{copy[activeNav]}</h2><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">{activeNav === 'Overview' ? 'One order, many small plots. A complete demand-first procurement loop for the school kitchen.' : `Connected ${activeNav.toLowerCase()} for the AgriLink pilot.`}</p></div>{(role === 'Buyer' || role === 'Coordinator') && <Button onClick={onNew}><Plus className="size-4" /> New order</Button>}</div> }

function Overview({ role, committed, progress, notified, onNotify, onOrder, onRoute }: { role: Role; committed: number; progress: number; notified: boolean; onNotify: () => void; onOrder: () => void; onRoute: () => void }) { return <><div className="grid gap-4 md:grid-cols-3"><Stat title="Active order value" value="₹36,000" detail="School kitchen · 200 kg" trend="+12.4%" icon={<CircleDollarSign className="size-4" />} /><Stat title="Committed volume" value={`${committed} kg`} detail="115% target · buffer ready" trend="On track" icon={<Wheat className="size-4" />} /><Stat title="Farmer realised" value="₹18/kg" detail="vs ₹13 mandi price" trend="+38.5%" icon={<Leaf className="size-4" />} /></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><Card><div className="flex flex-col justify-between gap-3 border-b border-border p-5 sm:flex-row sm:items-start"><div><div className="mb-2 flex items-center gap-2"><Badge>Order #AG-1042</Badge><Badge tone="live">Live</Badge></div><h3 className="font-serif text-xl font-bold">Fresh tomato · School kitchen</h3><p className="mt-1 text-sm text-muted-foreground">Delivery Monday, 20 October · 200 kg at ₹18/kg</p></div><Button onClick={onNotify} disabled={notified}>{notified ? <><Check className="size-4" /> Farmers notified</> : <><Send className="size-4" /> Notify matched farmers</>}</Button></div><div className="p-5"><div className="mb-4 flex items-center justify-between"><div><p className="text-sm font-semibold">Commitment tracker</p><p className="mt-1 text-xs text-muted-foreground">Target volume with 15% standby buffer</p></div><span className="font-mono text-sm font-semibold text-primary">{committed} / 200 kg</span></div><div className="relative h-3 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary transition-all duration-700" style={{ width: `${progress}%` }} /></div><div className="mt-2 flex justify-between font-mono text-[10px] text-muted-foreground"><span>0 kg</span><span>Target 200</span><span>Buffer 230</span></div><div className="mt-7 grid gap-3 sm:grid-cols-3"><Mini label="Accepted" value="200 kg" /><Mini label="Standby" value="30 kg" /><Mini label="Response" value="92%" /></div></div></Card><Cascade notified={notified} onNotify={onNotify} /></div><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_1.2fr]"><PriceProof /><CollectionRunway onRoute={onRoute} /></div></> }
function Stat({ title, value, detail, trend, icon }: { title: string; value: string; detail: string; trend: string; icon: React.ReactNode }) { return <Card className="p-5"><div className="mb-7 flex items-center justify-between"><span className="text-sm text-muted-foreground">{title}</span><div className="rounded-lg bg-secondary p-2 text-primary">{icon}</div></div><div className="flex items-end justify-between"><div><span className="font-serif text-3xl font-bold">{value}</span><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div><span className="text-xs font-semibold text-primary">{trend}</span></div></Card> }
function Mini({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-secondary p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-mono text-sm font-semibold">{value}</p></div> }
function Cascade({ notified, onNotify }: { notified: boolean; onNotify: () => void }) { return <div className="rounded-xl border border-border bg-primary p-5 text-primary-foreground"><div className="mb-8 flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-primary-foreground/60">Notification cascade</p><h3 className="mt-2 font-serif text-xl font-bold">Order finds the farmer.</h3></div><Bell className="size-5" /></div><div className="space-y-4">{channels.map((channel, index) => <div key={channel} className="flex items-center gap-3"><div className={`flex size-8 items-center justify-center rounded-full border ${index < (notified ? 4 : 3) ? 'border-primary-foreground/30 bg-primary-foreground/15' : 'border-primary-foreground/15'}`}>{index < (notified ? 4 : 3) ? <Check className="size-3.5" /> : <span className="font-mono text-[10px]">{index + 1}</span>}</div><div className="flex-1"><div className="flex items-center justify-between text-xs"><span>{channel}</span><span className="text-primary-foreground/50">{index < (notified ? 4 : 3) ? 'complete' : 'ready'}</span></div><div className="mt-1.5 h-1 rounded-full bg-primary-foreground/10"><div className={`h-full rounded-full bg-accent transition-all duration-500 ${index < (notified ? 4 : 3) ? 'w-full' : 'w-0'}`} /></div></div></div>)}</div><div className="mt-8 border-t border-primary-foreground/15 pt-4"><div className="flex items-center justify-between text-xs"><span className="text-primary-foreground/60">Matched farmers</span><span className="font-mono font-semibold">12 nearby</span></div>{!notified && <button onClick={onNotify} className="mt-4 text-xs font-semibold text-accent">Run next cascade <ChevronRight className="ml-1 inline size-3" /></button>}</div></div> }
function PriceProof() { return <Card className="p-5"><div className="mb-5 flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">Price proof</p><h3 className="mt-2 font-serif text-xl font-bold">Both sides gain.</h3></div><ShieldCheck className="size-5 text-primary" /></div><div className="space-y-4">{[['AGMARKNET mandi', '₹13', 'Live · today, 08:42', 'live'], ['Farmer realised', '₹18', 'AgriLink collection price', 'good'], ['DoCA retail', '₹28', 'Published · today', 'cached'], ['Buyer paid', '₹21', 'School kitchen contract', 'good']].map(([label, value, detail, tone]) => <div key={label} className="flex items-center justify-between border-b border-border pb-4"><div><p className="text-sm font-medium">{label}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div><span className={`font-serif text-2xl font-bold ${tone === 'good' ? 'text-primary' : ''}`}>{value}</span></div>)}</div><div className="mt-5 rounded-lg bg-secondary p-3 text-center"><span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Intermediary margin compressed by </span><span className="font-semibold text-primary">42%</span></div></Card> }
function CollectionRunway({ onRoute }: { onRoute: () => void }) { return <Card className="p-5"><div className="mb-5 flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">Today&apos;s movement</p><h3 className="mt-2 font-serif text-xl font-bold">Collection runway</h3></div><div className="flex items-center gap-2 rounded-full bg-secondary px-2.5 py-1 text-xs text-muted-foreground"><Cloud className="size-3.5" /> 28°C · clear</div></div><div className="grid gap-3 sm:grid-cols-3"><Mini label="Village pickups" value="04" /><Mini label="Optimised route" value="18.4 km" /><Mini label="Collection starts" value="09:30" /></div><div className="mt-5 flex items-center gap-3 rounded-lg bg-secondary/60 p-3"><div className="flex size-9 items-center justify-center rounded-lg bg-card text-primary"><Droplets className="size-4" /></div><div className="flex-1"><p className="text-xs font-semibold">Route is ready to dispatch</p><p className="mt-0.5 text-[11px] text-muted-foreground">Manifest includes 4 lots · 230 kg total</p></div><Button variant="ghost" onClick={onRoute}>View route <ChevronRight className="size-3" /></Button></div></Card> }

function OrderForm({ crop, setCrop, qty, setQty, onClose, onPost }: { crop: string; setCrop: (v: string) => void; qty: string; setQty: (v: string) => void; onClose: () => void; onPost: () => void }) { return <Card className="mb-6 border-primary/30 p-5"><div className="flex items-start justify-between"><div><Badge tone="live">AGMARKNET live</Badge><h3 className="mt-3 font-serif text-2xl font-bold">Post committed demand</h3><p className="mt-1 text-sm text-muted-foreground">The price source is shown before you send the order.</p></div><button onClick={onClose} aria-label="Close order form"><X className="size-5 text-muted-foreground" /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><label className="text-sm font-medium">Crop<select value={crop} onChange={(e) => setCrop(e.target.value)} className="mt-2 min-h-11 w-full rounded-lg border border-border bg-background px-3"><option>Tomato</option><option>Potato</option><option>Onion</option><option>Millets</option></select></label><label className="text-sm font-medium">Quantity<input value={qty} onChange={(e) => setQty(e.target.value)} type="number" className="mt-2 min-h-11 w-full rounded-lg border border-border bg-background px-3" /></label><div><p className="text-sm font-medium">Agreed price</p><div className="mt-2 flex min-h-11 items-center justify-between rounded-lg border border-border bg-secondary px-3"><span className="font-serif text-xl font-bold">₹18/kg</span><Badge tone="live">Live</Badge></div></div></div><div className="mt-5 flex flex-wrap justify-end gap-2"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button onClick={onPost}><ClipboardList className="size-4" /> Post order</Button></div></Card> }

function Orders({ role, orderPosted, onNew, advancePaid, onAdvance, notified, onNotify }: { role: Role; orderPosted: boolean; onNew: () => void; advancePaid: boolean; onAdvance: () => void; notified: boolean; onNotify: () => void }) { return <div className="grid gap-6 xl:grid-cols-[1.35fr_1fr]"><Card><div className="border-b border-border p-5"><div className="flex items-center justify-between"><div><Badge tone="live">{orderPosted ? 'New order posted' : 'Order #AG-1042'}</Badge><h3 className="mt-3 font-serif text-2xl font-bold">Fresh tomato · PM POSHAN kitchen</h3><p className="mt-1 text-sm text-muted-foreground">200 kg · delivery Monday 20 October · ₹18/kg</p></div><PackageCheck className="size-6 text-primary" /></div></div><div className="space-y-4 p-5"><Step done={true} title="Demand committed" detail="School kitchen order confirmed" /><Step done={notified} title="Farmers notified" detail={notified ? 'Four-tier cascade completed' : 'Send SMS, WhatsApp, IVR and call list'} action={!notified ? <Button onClick={onNotify}><Send className="size-4" /> Notify</Button> : undefined} /><Step done={advancePaid} title="Collection advance" detail={advancePaid ? 'Ledger instruction recorded at collection' : 'Advance is recorded when accepted lot is graded'} action={!advancePaid && role !== 'Buyer' ? <Button onClick={onAdvance}><Banknote className="size-4" /> Record advance</Button> : undefined} /><Step done={false} title="Delivery inspection" detail="Binding buyer confirmation at drop point" /></div></Card><div className="space-y-6"><Card className="p-5"><p className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Order source</p><h3 className="mt-2 font-serif text-xl font-bold">Demand before harvest</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">This order started with a buyer commitment. Farmers register crop and harvest windows first; no harvested lot waits for a buyer.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><Mini label="Buyer type" value="Institutional" /><Mini label="Channel rule" value="Perishable only" /></div></Card><PhoneFrame notified={notified} /></div></div> }
function Step({ done, title, detail, action }: { done: boolean; title: string; detail: string; action?: React.ReactNode }) { return <div className="flex items-center gap-4 rounded-lg border border-border p-4"><div className={`flex size-9 shrink-0 items-center justify-center rounded-full ${done ? 'bg-primary text-primary-foreground' : 'bg-secondary text-muted-foreground'}`}>{done ? <Check className="size-4" /> : <span className="font-mono text-xs">•</span>}</div><div className="flex-1"><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div>{action}</div> }
function PhoneFrame({ notified }: { notified: boolean }) { return <Card className="overflow-hidden bg-foreground p-3 text-background"><div className="rounded-[1.5rem] bg-card p-4 text-foreground"><div className="mb-4 flex items-center justify-between text-xs"><span className="font-semibold">AgriLink messages</span><Smartphone className="size-4" /></div><div className="space-y-3"><div className="ml-5 rounded-2xl rounded-br-sm bg-primary p-3 text-xs leading-5 text-primary-foreground">AgriLink: School kitchen needs 200 kg tomato by 20 Oct. You can commit 50 kg.</div><div className="mr-5 rounded-2xl rounded-bl-sm bg-secondary p-3 text-xs leading-5">{notified ? 'Accepted. Your 50 kg is reserved. Collection 09:30 at Kheda.' : 'Waiting for notification cascade...'}</div></div><div className="mt-5 flex items-center gap-2 rounded-full bg-secondary px-3 py-2 text-[11px] text-muted-foreground"><Phone className="size-3" /> IVR language: Gujarati</div></div></Card> }

function Network({ notified, onNotify }: { notified: boolean; onNotify: () => void }) { return <div className="grid gap-6 xl:grid-cols-[1.35fr_1fr]"><Card><div className="flex items-center justify-between border-b border-border p-5"><div><p className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Crop registry · 12 members</p><h3 className="mt-2 font-serif text-2xl font-bold">Matched for tomato</h3></div><Button onClick={onNotify} disabled={notified}>{notified ? <><Check className="size-4" /> Cascade sent</> : <><Send className="size-4" /> Notify matched</>}</Button></div><div className="divide-y divide-border">{farmers.map((farmer) => <div key={farmer.name} className="flex items-center gap-4 p-4"><div className={`flex size-10 items-center justify-center rounded-full ${farmer.color} font-mono text-xs text-primary-foreground`}>{farmer.name.split(' ').map((n) => n[0]).join('')}</div><div className="flex-1"><p className="text-sm font-semibold">{farmer.name}</p><p className="mt-1 text-xs text-muted-foreground">{farmer.village} · harvest window 17–19 Oct</p></div><div className="text-right"><p className="font-mono text-sm font-semibold">{farmer.kg} kg</p><Badge tone={farmer.status === 'Standby' ? 'warn' : 'good'}>{farmer.status}</Badge></div></div>)}</div></Card><Card className="p-5"><p className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Matching logic</p><h3 className="mt-2 font-serif text-xl font-bold">Crop registry, not a listing board.</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">The order matches crop, overlapping harvest window, and distance from the buyer. Commitments accumulate to 115%; the final 15% is a standby buffer.</p><div className="mt-5 space-y-3"><Mini label="Nearby farmers" value="12" /><Mini label="Overlap window" value="4 days" /><Mini label="Standby buffer" value="30 kg" /></div></Card></div> }

function Collection({ grade, setGrade, saved, onSave, advancePaid, onAdvance }: { grade: 'A' | 'B' | 'Rejected'; setGrade: (v: 'A' | 'B' | 'Rejected') => void; saved: boolean; onSave: () => void; advancePaid: boolean; onAdvance: () => void }) { return <div className="grid gap-6 xl:grid-cols-[1.2fr_1fr]"><Card className="p-5"><div className="flex items-start justify-between"><div><Badge>Lot LOT-2042</Badge><h3 className="mt-3 font-serif text-2xl font-bold">GradeCam collection</h3><p className="mt-1 text-sm text-muted-foreground">Ramesh Kumar · 50 kg tomato · Kheda pickup</p></div><Camera className="size-6 text-primary" /></div><div className="mt-6 flex aspect-[4/3] items-center justify-center rounded-xl border border-dashed border-primary/40 bg-secondary/50"><div className="text-center"><Camera className="mx-auto size-10 text-primary" /><p className="mt-3 text-sm font-semibold">Camera capture ready</p><p className="mt-1 text-xs text-muted-foreground">Gallery upload disabled for traceability</p><Button variant="ghost" onClick={() => setGrade('A')}><Camera className="size-4" /> Capture lot</Button></div></div><div className="mt-5 flex flex-wrap gap-2"><Button onClick={onSave} disabled={saved}><BadgeCheck className="size-4" /> {saved ? 'Grade saved' : 'Accept grade'}</Button><Button variant="secondary" onClick={() => setGrade(grade === 'A' ? 'B' : 'A')}>Override</Button><Button variant="secondary" onClick={() => setGrade('Rejected')}><AlertTriangle className="size-4" /> Reject</Button></div></Card><Card className="p-5"><p className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Vision result · fallback ready</p><h3 className="mt-2 font-serif text-xl font-bold">AI says Grade {grade}</h3><div className="mt-5 grid gap-3 sm:grid-cols-2"><Mini label="Confidence" value={grade === 'Rejected' ? '96%' : '91%'} /><Mini label="Defects found" value={grade === 'A' ? '0 visible' : grade === 'B' ? 'minor marks' : 'quality fail'} /></div><div className="mt-5 rounded-lg bg-secondary p-4 text-sm leading-6 text-muted-foreground">The transaction never blocks on AI. If the model fails or confidence drops below threshold, the coordinator enters a manual grade and records the reason.</div><div className="mt-5 border-t border-border pt-5"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Collection advance</p><p className="mt-1 text-xs text-muted-foreground">₹450 ledger instruction · 50 kg × ₹18 × 50%</p></div><Button onClick={onAdvance} disabled={advancePaid}>{advancePaid ? <><Check className="size-4" /> Recorded</> : 'Record advance'}</Button></div></div></Card></div> }

function RoutesScreen({ delivery, setDelivery }: { delivery: 'pending' | 'confirmed' | 'flagged'; setDelivery: (v: 'pending' | 'confirmed' | 'flagged') => void }) { return <div className="grid gap-6 xl:grid-cols-[1.25fr_1fr]"><Card className="overflow-hidden"><div className="border-b border-border p-5"><div className="flex items-center justify-between"><div><Badge tone="good">Optimised · 18.4 km</Badge><h3 className="mt-3 font-serif text-2xl font-bold">Collection manifest</h3><p className="mt-1 text-sm text-muted-foreground">4 village pickups → school kitchen drop</p></div><Route className="size-6 text-primary" /></div></div><div className="relative min-h-[330px] bg-secondary p-6"><div className="absolute inset-8 rounded-xl border border-primary/20 bg-background/60" /><div className="relative flex h-[280px] flex-col justify-between"><Stop n="1" place="Kheda" detail="Ramesh · 50 kg" /><div className="ml-10 border-l-2 border-dashed border-primary/50 pl-8"><Stop n="2" place="Borsad" detail="Savitri · 70 kg" /><div className="my-5 border-l-2 border-dashed border-primary/50 pl-8"><Stop n="3" place="Vasad" detail="Mohan · 80 kg" /></div><Stop n="4" place="PM POSHAN kitchen" detail="Drop · 200 kg" /></div></div></div></Card><div className="space-y-6"><Card className="p-5"><p className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Route service · static demo</p><h3 className="mt-2 font-serif text-xl font-bold">Optimised over naive</h3><div className="mt-5 grid gap-3 sm:grid-cols-2"><Mini label="Naive distance" value="31.2 km" /><Mini label="Saved" value="12.8 km" /></div><div className="mt-5 flex items-center gap-3 rounded-lg bg-secondary p-3 text-xs text-muted-foreground"><MapPin className="size-4 text-primary" /> Coordinates are seeded for demo; production uses OR-Tools + OpenStreetMap.</div></Card><Card className="p-5"><p className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Buyer delivery confirmation</p><h3 className="mt-2 font-serif text-xl font-bold">Inspection is binding.</h3><p className="mt-2 text-sm text-muted-foreground">No returns flow. Confirm or flag the delivered lot at the drop point.</p><div className="mt-5 flex flex-wrap gap-2"><Button onClick={() => setDelivery('confirmed')} disabled={delivery === 'confirmed'}><Check className="size-4" /> {delivery === 'confirmed' ? 'Delivery confirmed' : 'Confirm delivery'}</Button><Button variant="secondary" onClick={() => setDelivery('flagged')} disabled={delivery === 'flagged'}><AlertTriangle className="size-4" /> Flag mismatch</Button></div>{delivery !== 'pending' && <div className="mt-4"><Badge tone={delivery === 'confirmed' ? 'good' : 'warn'}>{delivery === 'confirmed' ? 'Confirmed in ledger' : 'Mismatch flagged'}</Badge></div>}</Card></div></div> }
function Stop({ n, place, detail }: { n: string; place: string; detail: string }) { return <div className="flex items-center gap-3"><div className="flex size-8 items-center justify-center rounded-full bg-primary font-mono text-xs font-bold text-primary-foreground">{n}</div><div className="rounded-lg border border-border bg-card px-3 py-2 shadow-sm"><p className="text-xs font-semibold">{place}</p><p className="mt-0.5 text-[10px] text-muted-foreground">{detail}</p></div></div> }

function Settlements({ role, delivery }: { role: Role; delivery: 'pending' | 'confirmed' | 'flagged' }) { return <div className="grid gap-6 xl:grid-cols-[1.2fr_1fr]"><Card><div className="border-b border-border p-5"><div className="flex items-center justify-between"><div><Badge tone={delivery === 'confirmed' ? 'good' : 'cached'}>{delivery === 'confirmed' ? 'Ready to settle' : 'Ledger preview'}</Badge><h3 className="mt-3 font-serif text-2xl font-bold">Farmer receipt · Ramesh Kumar</h3><p className="mt-1 text-sm text-muted-foreground">LOT-2042 · Grade A · 50 kg tomato</p></div><Receipt className="size-6 text-primary" /></div></div><div className="space-y-4 p-5"><Line label="Graded weight" value="50 kg" /><Line label="Agreed price" value="× ₹18/kg" /><Line label="Gross value" value="₹900" strong /><Line label="Collection advance paid" value="− ₹450" /><Line label="Transport share" value="− ₹36" /><div className="border-t border-border pt-4"><Line label="Net payable to farmer" value="₹414" strong /></div></div><div className="border-t border-border bg-secondary/60 p-5"><p className="text-xs leading-5 text-muted-foreground">Funds move buyer → FPO bank account → farmer. AgriLink records and instructs the ledger but never holds funds.</p></div></Card><div className="space-y-6"><PriceProof /><Card className="p-5"><p className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Farmer view</p><h3 className="mt-2 font-serif text-xl font-bold">One receipt, all the proof.</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{role === 'Farmer' ? 'Your sale receipt shows the grade, agreed price, advance, transport share, and final payable.' : 'Switch the header role to Farmer to demo the low-bandwidth receipt view.'}</p><Button variant="ghost" onClick={() => window.print()}><Receipt className="size-4" /> Print receipt</Button></Card></div></div> }
function Line({ label, value, strong = false }: { label: string; value: string; strong?: boolean }) { return <div className={`flex items-center justify-between ${strong ? 'text-lg font-semibold' : 'text-sm'}`}><span className={strong ? 'font-serif' : 'text-muted-foreground'}>{label}</span><span className={strong ? 'font-serif text-primary' : 'font-mono'}>{value}</span></div> }

export { SHELF_LIFE_ROUTING }
